spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stbdb?characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.beautiful.stay
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.yml